#!/usr/bin/env bash

. "$BASH_IT/themes/my-powerline/my-powerline.base.bash"

PROMPT_CHAR=${MY_POWERLINE_PROMPT_CHAR:=""}
MY_POWERLINE_LEFT_SEPARATOR=${MY_POWERLINE_LEFT_SEPARATOR:=""}

USER_INFO_SSH_CHAR=${MY_POWERLINE_USER_INFO_SSH_CHAR:=" "}
USER_INFO_THEME_PROMPT_COLOR=27
USER_INFO_THEME_PROMPT_COLOR_SUDO=196

PYTHON_VENV_CHAR=${MY_POWERLINE_PYTHON_VENV_CHAR:="❲p❳ "}
CONDA_PYTHON_VENV_CHAR=${MY_POWERLINE_CONDA_PYTHON_VENV_CHAR:="❲c❳ "}
PYTHON_VENV_THEME_PROMPT_COLOR=35

SCM_NONE_CHAR=""
SCM_GIT_CHAR=${MY_POWERLINE_SCM_GIT_CHAR:="⎇  "}
SCM_THEME_PROMPT_DIRTY=" ${bold_red}✗${reset_color}"
SCM_THEME_PROMPT_CLEAN=" ${bold_green}✓${reset_color}"
SCM_GIT_CHAR="${bold_green}±${reset_color} "
SCM_SVN_CHAR="${bold_cyan}⑆${reset_color} "
SCM_HG_CHAR="${bold_red}☿${reset_color} "
SCM_THEME_PROMPT_CLEAN_COLOR=25
SCM_THEME_PROMPT_DIRTY_COLOR=1
SCM_THEME_PROMPT_STAGED_COLOR=30
SCM_THEME_PROMPT_UNSTAGED_COLOR=92
SCM_THEME_PROMPT_COLOR=${SCM_THEME_PROMPT_CLEAN_COLOR}

RVM_THEME_PROMPT_PREFIX=""
RVM_THEME_PROMPT_SUFFIX=""
RBENV_THEME_PROMPT_PREFIX=""
RBENV_THEME_PROMPT_SUFFIX=""
RUBY_THEME_PROMPT_COLOR=161
RUBY_CHAR=${MY_POWERLINE_RUBY_CHAR:="❲r❳ "}

CWD_THEME_PROMPT_COLOR=39

LAST_STATUS_THEME_PROMPT_COLOR=88

CLOCK_THEME_PROMPT_COLOR=27
CLOCK_THEME_PROMPT_COLOR_SUDO=196

BATTERY_AC_CHAR=${BATTERY_AC_CHAR:="⚡"}
BATTERY_STATUS_THEME_PROMPT_GOOD_COLOR=2
BATTERY_STATUS_THEME_PROMPT_LOW_COLOR=208
BATTERY_STATUS_THEME_PROMPT_CRITICAL_COLOR=160

THEME_CLOCK_FORMAT=${THEME_CLOCK_FORMAT:="%H:%M"}

IN_VIM_THEME_PROMPT_COLOR=245
IN_VIM_THEME_PROMPT_TEXT="vim"

HOST_THEME_PROMPT_COLOR=0

MY_POWERLINE_PROMPT=${MY_POWERLINE_PROMPT:="user_info cwd scm python_venv in_vim "}

safe_append_prompt_command __my_powerline_prompt_command
